---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: spring-demo