---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
  labels:
    app: spring-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: registry.gitlab.com/rdev2021/spring-demo:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: spring-demo-secret
                key: mysql_hostname
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: spring-demo-secret
                key: mysql_username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: spring-demo-secret
                key: mysql_password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
