---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: spring-demo
---
apiVersion: v1
kind: Service
metadata:
  name: mysqlhost
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqlhost
subsets:
  - addresses:
      - ip: 192.168.1.29
    ports:
      - port: 3306
